version: "3.8"

services:

  spark-master:
    build:
      context: .
      dockerfile: ./config/dockerfile.spark
    #image: sabastiao-spark:3.5
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j.properties
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    ports:
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master comms
    volumes:
      - ./config/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./logs/master:/opt/bitnami/spark/logs/events
      - ./src:/app

  spark-worker-1:
    build:
      context: .
      dockerfile: ./config/dockerfile.spark
    #image: sabastiao-spark:3.5
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j.properties
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./config/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./logs/master:/opt/bitnami/spark/logs/events

  spark-worker-2:
    build:
      context: .
      dockerfile: ./config/dockerfile.spark
    #image: sabastiao-spark:3.5
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j.properties
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - spark-master
    ports:
      - "8082:8081"  # Porta local 8082 mapeia para porta 8081 do container
    volumes:
      - ./config/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./logs/master:/opt/bitnami/spark/logs/events

  spark-history-server:
    image: rangareddy1988/spark-history-server:3.5.0
    container_name: spark-history-server
    hostname: spark-history-server
    environment:
      - SPARK_HISTORY_UI_PORT=18080
      - SPARK_DAEMON_MEMORY=2g
      - SPARK_HISTORY_RETAINEDAPPLICATIONS=100
      - SPARK_HISTORY_UI_MAXAPPLICATIONS=50
      - SPARK_HISTORY_STORE_MAXDISKUSAGE=20g
      - SPARK_HISTORY_FS_LOG_DIRECTORY=/opt/bitnami/spark/logs/events
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/bitnami/spark/logs/events
      - SPARK_LOG_CONF=/opt/bitnami/spark/conf/log4j.properties
    ports:
      - "18080:18080"
      - "4040:4040"
    volumes:
      - ./logs/master:/opt/bitnami/spark/logs/events
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
